baseURL: https://faceafacecomaestatistica
languageCode: pt-en
title: Blog pessoal para brincar com estatística
theme: "hugo-refresh"
# theme: ../..

#########################################
######## Descomente esta opcao##########
#########################################
# Estas opções especificam onde procurar as imagens usadas nesta configuração
# O valor padrão é o diretório "ativo" ("asset") deste tema
# assetDir: "static" 

# Opção para especificar o idioma padrão do tema
# Ou seja, o idioma de destino de sua raiz 
DefaultContentLanguage: pt

## Opção para desativar o idioma adicional em seu site.
disableLanguages: ["en"]

disableKinds: ["sitemap","RSS"]

# Opção para especificar que todos os links serão abertos em uma nova guia.
blackfriday:
  hrefTargetBlank: true

Taxonomies:
  tag: "tags"

# As fontes suportadas são:
# https://fonts.google.com/

# Ícones retirados de:
# https://konpa.github.io/devicon/
# https://bulkitv2.cssninja.io/_components-icons-fa.html

params:
  # parâmetros usados para especificar o número de artigos em cada linha
  # para as páginas de resumo, as opções possíveis são: 2, 3, 4, 5 ou 6
  articlesPerRow: 3 

  # opção para especificar a imagem favicon do site
  # o caminho é relativo à pasta "assetDir" desta configuração
  favicon: "/images/favicon.svg"

  # parâmetro usado para especificar se você deseja minimizar o js importado
  jsMinify: false
  # parâmetro usado para especificar se você deseja minificar o css importado
  cssMinify: false
  # parâmetros usados para especificar se você deseja calcular a integridade css
  cssIntegrity: true
  # parâmetros usados para especificar se você deseja calcular a integridade js
  jsIntegrity: true
  # opção para especificar a cor principal do tema
  mainColour: "#0000FF"

  # opções de resumo
  summary:
    # opção para especificar a imagem padrão na lista de resumo
    # a pasta inicial é configurada em "assetDir" deste arquivo
    defaultImage : "/images/default_summary.jpg"
  
  # loading options
  loading:
    # opção para especificar a imagem de carregamento
    # a pasta inicial é configurada em "assetDir" deste arquivo
    image: "/images/loaders/rings.svg"

  # opções das páginas principais
  mainPage:
    # opção para especificar a fonte principal do tema
    fontFamily: "Open Sans" 

  # opções da barra lateral
  sidebar:
    # opção para especificar o logotipo da barra lateral
    # a pasta inicial é configurada em "assetDir" deste arquivo
    logo: "/images/refresh-square.svg"
    # option to specify the font of the sidebar
    fontFamily: "Open Sans" # "Open Sans"

  # opções da barra de navegação
  navbar:
    # opção para especificar a fonte usada na barra de navegação
    fontFamily: "Open Sans"
    # opção de mostrar os pequenos logotipos ao lado dos itens da barra de navegação
    showIcons: false
    
  # Opções de página 404
  pagNotFound:
    # opção para especificar a imagem principal da barra lateral
    # a pasta inicial é configurada em "assetDir" deste arquivo
    image: "/images/avataaars_404.png"
    # opção para especificar o título da página 404
    title: 404 Page Not Found :(
    # opção para especificar o subtítulo da página 404
    subtitle: Esta não é a página que você estava procurando ...
    # opção para especificar a largura da imagem na página 404
    imageWidth: 500px

  # opções da página inicial
  homepage:
    # essas opções permitem que você especifique se deseja um link para a página inicial
    # it can be: "none", "menu", "footer" or "menu+footer" 
    # (pode ser: "nenhum", "menu", "rodapé" ou "menu + rodapé")
    # linkPosition: "footer" (linkPosition: "rodapé")
    # essas opções permitem que você especifique o texto do link para a página inicial
    # linkText: "Homepage" (linkText: "Página inicial")
    # opção para especificar o título na página inicial
    title: Face a Face com a Estatística
    # opção para especificar o subtítulo na página inicial
    subtitle: 
    # opção para especificar a imagem na página inicial
    image: "/images/avataaars.png" # worker.svg 
    # opção para especificar a largura da imagem na página inicial
    imageWidth: 500px

  # footer options (opções de rodapé)
  footer:
    # opção para especificar o logotipo no rodapé
    # a pasta inicial é configurada em "assetDir" deste arquivo
    logo: "/images/refresh-square.svg"
    # opção de especificar seu e-mail de contato no rodapé
    email: 
      link: andresondez@hotmail.com
      title: andresondez@hotmail.com
    # opção de especificar seu perfil do LinkedIn no rodapé
    linkedin: 
      link: https://www.linkedin.com/in/andreson-azevedo/
      title: andreson-azevedo/
    # opção de especificar sua conta do Facebook no rodapé; 
    # ** descomente ** as linhas abaixo para mostrar no rodapé
    # facebook: 
    #   link: your.username
    #   title: Facebook
    # option to specify your github account in the footer; 
    # **uncomment** the below lines to show in footer
    # github: 
    #   link: username
    #   title: Github
    # option to specify your twitter username in the footer; 
    # **uncomment** the below lines to show in footer
    # twitter: 
    #    link: username
    #    title: Twitter
    # option to specify your instagram username in the footer; 
    # **uncomment** the below lines to show in footer
    # instagram: 
    #    link: username
    #    title: Instagram
    # option to specify the copyright in the footer
    copyright: Face a Face com a Estatística - 2021

###################################################################
################## multilanguage support options ##################
###################################################################
languages:
  pt:
    languageName:       Portuguese
    weight:             1
  en:
    languageName:       English
    weight:             2
    # Ao especificar parâmetros diferentes para um idioma diferente
    # você precisa especificar todos os subparâmetros obrigatórios também.
    #Por exemplo: se você especificar o parâmetro "homepage", será necessário
    #       especifique todos os subparâmetros obrigatórios, por exemplo: "título".
    # Veja o exemplo abaixo:
    params:
      homepage:
        title: Face to Face with Statistics
        subtitle: 
        image: "/images/avataaars.png" # worker.svg 
        imageWidth: 500px
      
      # Alguns subparâmetros do parâmetro "rodapé"
      # pode ser omitido porque o código permite que eles sejam 
      # perdidos, mas eles serão tratados como se não existissem,
      # ou seja, os parâmetros do idioma padrão
      # não será herdado.
      footer:
        logo: "/images/refresh-square.svg"
        email: 
          link: andresondez@hotmail.com
          title: andresondez@hotmail.com
        linkedin: 
          link: https://www.linkedin.com/in/andreson-azevedo/
          title: andreson-azevedo/
        # facebook: 
        #   link: your.username
        #   title: Facebook 
        # twitter: 
        #   link: username
        #   title: Twitter
        # instagram: 
        #   link: username
        #   title: Instagram
        # github: 
        #   link: username
        #   title: Github
        copyright: Face to Face with Statistics - 2021
      

markup:
  goldmark:
    renderer:
      unsafe: true
